# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"9\n\x13\x41uthenticateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\x0bListRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\t\"<\n\x0bSendRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"\x1f\n\x0e\x44\x65liverRequest\x12\r\n\x05token\x18\x01 \x01(\t\"0\n\rDeleteRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"3\n\x0eStringResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t\" \n\rEmptyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf5\x01\n\x0eMessageService\x12\x37\n\x0c\x41uthenticate\x12\x14.AuthenticateRequest\x1a\x0f.StringResponse\"\x00\x12\'\n\x04List\x12\x0c.ListRequest\x1a\x0f.StringResponse\"\x00\x12&\n\x04Send\x12\x0c.SendRequest\x1a\x0e.EmptyResponse\"\x00\x12-\n\x07\x44\x65liver\x12\x0f.DeliverRequest\x1a\x0f.StringResponse\"\x00\x12*\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0e.EmptyResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATEREQUEST._serialized_start=17
  _AUTHENTICATEREQUEST._serialized_end=74
  _LISTREQUEST._serialized_start=76
  _LISTREQUEST._serialized_end=121
  _SENDREQUEST._serialized_start=123
  _SENDREQUEST._serialized_end=183
  _DELIVERREQUEST._serialized_start=185
  _DELIVERREQUEST._serialized_end=216
  _DELETEREQUEST._serialized_start=218
  _DELETEREQUEST._serialized_end=266
  _STRINGRESPONSE._serialized_start=268
  _STRINGRESPONSE._serialized_end=319
  _EMPTYRESPONSE._serialized_start=321
  _EMPTYRESPONSE._serialized_end=353
  _MESSAGESERVICE._serialized_start=356
  _MESSAGESERVICE._serialized_end=601
# @@protoc_insertion_point(module_scope)
